### ISSUE TITLE
EDIV vsetvli syntax

### ISSUE THREAD

**Issue by jim-wilson** [riscv/riscv-v-spec#83]
The EDIV section doesn't clearly specify the strings the assembler should use with vsetvli for setting the vediv field.  One code example uses "vdiv4" and another code sample uses "d4".  The "d4" is more consistent with the "e8" and "m4" documented in the vsetvli section, so I'd suggest dX for X=1,2,4,8.

One code sample also uses "ve32" should should be "e32".

**Comment by kasanovic** [comment]
Couldn't find these now, so must have been fixed meantime.

**Comment by jim-wilson** [comment]
I saw the git log entry that mentioned that dX was the new syntax, and so submitted pull requests to fix assembly code that Andrew merged in.

However, we are still missing a table to document the assembly syntax.  Section 6.1 has a table "Suggested assembler names used for vtypei setting" that documents the eX and mX values for vsetvli, but the dX values for the Zvediv extension are not documented anywhere, they are just used in a few assembly code samples.

**Comment by kasanovic** [comment]
Added clarification.

Krste


>>>>> On Fri, 22 Feb 2019 21:21:22 +0000 (UTC), Jim Wilson <notifications@github.com> said:

| I saw the git log entry that mentioned that dX was the new syntax, and so submitted pull requests to fix
| assembly code that Andrew merged in.

| However, we are still missing a table to document the assembly syntax. Section 6.1 has a table "Suggested
| assembler names used for vtypei setting" that documents the eX and mX values for vsetvli, but the dX values for
| the Zvediv extension are not documented anywhere, they are just used in a few assembly code samples.

| —
| You are receiving this because you modified the open/close state.
| Reply to this email directly, view it on GitHub, or mute the thread.*
